// Lucide Icons mapping to replace the custom SVG icons
import {
  ChevronLeft,
  Eye,
  EyeOff,
  Clock,
  MoreVertical,
  Video,
  AudioWaveform,
  File,
  Folder,
  Grid3X3,
  Download,
  Upload,
  Plus,
  X,
  CheckCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Bolt,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  FolderOpen,
  DollarSign,
  Trash2,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  Mail,
  Lock,
  Calendar,
  User,
  UserCircle,
  List,
  Table,
  FileText,
  PieChart,
  Box,
  Plug,
  MessageCircle,
  Send,
  Copy,
  Smartphone,
  ShoppingCart,
  Phone,
  Truck,
  TrendingUp,
  MoreHorizontal,
  Star,
  Users,
  Brain,
  Package,
  EyeIcon as LucideEye, // Renamed to avoid conflict
  Calendar as CalendarIcon,
  Mail as MailIcon,
  User as UserIcon,
  File as FileIcon,
  Folder as FolderIcon,
  MessageCircle as MessageIcon,
  ShoppingCart as CartIcon,
  Phone as PhoneIcon,
  Truck as TruckIcon,
  TrendingUp as TrendingUpIcon
} from "lucide-react";

// Export commonly used icons with their original names
export {
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Eye,
  EyeOff,
  Clock,
  MoreVertical,
  Video,
  AudioWaveform,
  File,
  Folder,
  Grid3X3,
  Download,
  Upload,
  Plus,
  X,
  CheckCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Bolt,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  FolderOpen,
  DollarSign,
  Trash2,
  Mail,
  Lock,
  Calendar,
  User,
  UserCircle,
  List,
  Table,
  FileText,
  PieChart,
  Box,
  Plug,
  Send,
  Copy,
  Smartphone,
  ShoppingCart,
  Phone,
  Truck,
  TrendingUp,
  // Aliases with original names
  LucideEye as EyeIcon,
  CalendarIcon as CalenderIcon,
  MailIcon as EnvelopeIcon,
  MailIcon, // Export the MailIcon that was imported as Mail
  FileIcon,
  FolderIcon,
  MessageIcon as ChatIcon,
  PhoneIcon as CallIcon,
  PhoneIcon, // Also export PhoneIcon directly
  TruckIcon as TruckDelivery,
  TruckIcon, // Also export TruckIcon directly
  TrendingUpIcon as ShootingStarIcon,
  TrendingUpIcon, // Also export TrendingUpIcon directly
  // Additional mappings for named imports
  MoreHorizontal as HorizontaLDots,
  Package as BoxCubeIcon, // BoxCube maps to Package, so BoxCubeIcon also maps to Package
  Grid3X3 as GridIcon, // Map GridIcon to Grid3X3
  Box as BoxIcon,
  ChevronDown as ChevronDownIcon,
  ChevronDown as AngleDownIcon,
  ChevronUp as AngleUpIcon,
  ArrowDown as ArrowDownIcon,
  ArrowUp as ArrowUpIcon,
  Box as BoxIconLine,
  Users as GroupIcon,
  Brain as AiIcon // Map Brain to AiIcon
};

// For the remaining icons, we'll use generic placeholders for now
// as the complete mapping would require more specific analysis