// Lucide Icons mapping to replace the custom SVG icons
import { 
  ChevronLeft, 
  Eye, 
  EyeOff, 
  Clock, 
  MoreVertical, 
  Video,
  AudioWaveform,
  File,
  Folder,
  Grid3X3,
  Download,
  Upload,
  Plus,
  X,
  CheckCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Bolt,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  FolderOpen,
  DollarSign,
  Trash2,
  ChevronUp,
  ChevronDown,
  ChevronRight,
  Mail,
  Lock,
  Calendar,
  User,
  UserCircle,
  List,
  Table,
  FileText,
  PieChart,
  Box,
  Plug,
  MessageCircle,
  Send,
  Copy,
  Smartphone,
  ShoppingCart,
  Phone,
  Truck,
  TrendingUp,
  EyeIcon as LucideEye, // Renamed to avoid conflict
  Calendar as CalendarIcon,
  Mail as MailIcon,
  User as UserIcon,
  File as FileIcon,
  Folder as FolderIcon,
  MessageCircle as MessageIcon,
  ShoppingCart as CartIcon,
  Phone as PhoneIcon,
  Truck as TruckIcon,
  TrendingUp as TrendingUpIcon
} from "lucide-react";

// Export commonly used icons with their original names
export {
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronDown,
  Eye,
  EyeOff,
  Clock,
  MoreVertical,
  Video,
  AudioWaveform,
  File,
  Folder,
  Grid3X3,
  Download,
  Upload,
  Plus,
  X,
  CheckCircle,
  AlertCircle,
  Info,
  AlertTriangle,
  Bolt,
  ArrowUp,
  ArrowDown,
  ArrowRight,
  FolderOpen,
  DollarSign,
  Trash2,
  Mail,
  Lock,
  Calendar,
  User,
  UserCircle,
  List,
  Table,
  FileText,
  PieChart,
  Box,
  Plug,
  Send,
  Copy,
  Smartphone,
  ShoppingCart,
  Phone,
  Truck,
  TrendingUp,
  // Aliases with original names
  LucideEye as EyeIcon,
  CalendarIcon as CalenderIcon,
  MailIcon as EnvelopeIcon,
  UserIcon as UserIcon,
  FileIcon,
  FolderIcon,
  MessageIcon as ChatIcon,
  CartIcon as CartIcon,
  PhoneIcon as CallIcon,
  TruckIcon as TruckDelivery,
  TrendingUpIcon as ShootingStarIcon
};

// For the remaining icons, we'll use generic placeholders for now
// as the complete mapping would require more specific analysis